// Why: the installed extension cannot import Orca modules at runtime.
export function getPiAgentStatusPostQueueSourceLines(): string[] {
  return [
    '// Why: preserve receiver reset/text events, not arbitrary fields on a later status.',
    'type HookPost = { hookEventName: string; extra: Record<string, unknown>; metadata: Record<string, unknown>; ompRuntime: boolean }',
    'const MAX_PENDING_POST_GROUPS = 8',
    'let postScope = 0',
    'let activePost = false',
    'const pendingPostGroups: { scope: number; posts: HookPost[] }[] = []',
    '',
    '// Why: Pi 0.85 ctx.model/ctx.thinkingLevel captured per event by the default',
    '// export below; runtime evidence of what the session actually runs.',
    "let observedModel = ''",
    "let observedThinking = ''",
    '',
    'function observedOptionsPayload(): Record<string, unknown> {',
    '  const options: Record<string, unknown> = {}',
    '  if (observedModel) options.model = observedModel',
    '  if (observedThinking) options.thinking_level = observedThinking',
    '  return options',
    '}',
    '',
    'function post(hookEventName: string, extra: Record<string, unknown> = {}): void {',
    // Why: runtime-observed model/thinking ride every post; explicit extras win.
    '  const extraWithOptions = { ...observedOptionsPayload(), ...extra }',
    '  const ompRuntime = isOmpRuntime()',
    "  if (hookEventName === 'session_start' || hookEventName === 'before_agent_start') postScope += 1",
    '  let group = pendingPostGroups[pendingPostGroups.length - 1]',
    '  if (!group || group.scope !== postScope) {',
    '    group = { scope: postScope, posts: [] }',
    '    pendingPostGroups.push(group)',
    '    // Why: overload evicts whole old groups, never a prompt while retaining its reply.',
    '    if (pendingPostGroups.length > MAX_PENDING_POST_GROUPS) pendingPostGroups.shift()',
    '  }',
    '  // Why: at most a boundary, latest assistant message and latest status per group.',
    '  group.posts = group.posts.filter((entry) =>',
    "    entry.hookEventName === 'session_start' || entry.hookEventName === 'before_agent_start' ||",
    "    (entry.hookEventName === 'message_end' && hookEventName !== 'message_end')",
    '  )',
    '  group.posts.push({ hookEventName, extra: extraWithOptions, metadata: getPostSessionMetadata(ompRuntime), ompRuntime })',
    '  drainPosts()',
    '}',
    '',
    'function drainPosts(): void {',
    '  if (activePost) return',
    '  const group = pendingPostGroups[0]',
    '  if (!group) return',
    '  const next = group.posts.shift()!',
    '  if (group.posts.length === 0) pendingPostGroups.shift()',
    '  activePost = true',
    '  void postOnce(next.hookEventName, next.extra, next.metadata, next.ompRuntime)',
    '    .catch(() => {})',
    '    .finally(() => {',
    '      activePost = false',
    '      drainPosts()',
    '    })',
    '}',
    ''
  ]
}
