/** Real Pi/OMP/prime/OpenCode/mimo source, overlay, and primary dir keys.
 *  Isolation strips these from inherited env; no isolated-home fallback is set. */
export const AGENT_RUNTIME_DIR_ENV_KEYS = [
  'ORCA_PI_SOURCE_AGENT_DIR',
  'ORCA_PI_CODING_AGENT_DIR',
  'PI_CODING_AGENT_DIR',
  'ORCA_OMP_SOURCE_AGENT_DIR',
  'ORCA_OMP_CODING_AGENT_DIR',
  'ORCA_OMP_STATUS_EXTENSION',
  'ORCA_PRIME_AGENT_SOURCE_AGENT_DIR',
  'ORCA_PRIME_AGENT_STATUS_EXTENSION',
  'PRIME_AGENT_CODING_AGENT_DIR',
  'ORCA_OPENCODE_SOURCE_CONFIG_DIR',
  'ORCA_OPENCODE_CONFIG_DIR',
  'OPENCODE_CONFIG',
  'OPENCODE_CONFIG_DIR',
  'OPENCODE_CONFIG_CONTENT',
  'OPENCODE_SOURCE_CONFIG_DIR',
  'ORCA_MIMOCODE_SOURCE_HOME',
  'ORCA_MIMOCODE_HOME',
  'MIMOCODE_HOME'
] as const
